layout_spectrum: 0.4849624
color:
  saturation: 0.3893662
  brandStrength: 0.4924812
  lightness: 0.07894735
  brandColors:
    - '#01013D'
    - '#FFFFC0'
    - '#018891'
    - '#02BD98'
    - '#ACD79A'
  rhythmicContrast: 0
typography_spectrum: 0.3055854
name: The Art of Whore
